/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:e0d8c6aa-5e20-4161-9f43-4ec7fd3eb82c",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_PaQY0Ts8V",
    "aws_user_pools_web_client_id": "5lorvesk6vc3cp6pcas7led9kp",
    "oauth": {
        "domain": "urz4hctfbkgw-staging.auth.sa-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "instajoaquin://",
        "redirectSignOut": "instajoaquin://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://uw4js4e2gnefznvynisds7nuwe.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ubnjj7nnhzhs5eo2lcca5qnwfq"
};


export default awsmobile;
