/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_appsync_graphqlEndpoint": "https://4w5uw6wefzflpoaipz36nazbbi.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "sa-east-1:84d369b1-3471-402d-9c87-c22e62f904a7",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_joWVi7ss0",
    "aws_user_pools_web_client_id": "76huf6ivppgr79mdavinn3vvpu",
    "oauth": {
        "domain": "urz4hctfbkgw-production.auth.sa-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "instajoaquin://",
        "redirectSignOut": "instajoaquin://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "instagramclone-joa-media03802-production",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
