name: Build and deploy app to staging

on:
  workflow_dispatch:
  push:
    branches:
      - staging
      # - develop

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AMPLIFY_FACEBOOK_CLIENT_ID_STAGING: ${{secrets.AMPLIFY_FACEBOOK_CLIENT_ID_STAGING}}
  AMPLIFY_FACEBOOK_CLIENT_SECRET_STAGING: ${{secrets.AMPLIFY_FACEBOOK_CLIENT_SECRET_STAGING}}
  AMPLIFY_GOOGLE_CLIENT_ID: ${{secrets.AMPLIFY_GOOGLE_CLIENT_ID}}
  AMPLIFY_GOOGLE_CLIENT_SECRET: ${{secrets.AMPLIFY_GOOGLE_CLIENT_SECRET}}

jobs:
  deploy-backend:
    name: deploy backend to staging env
    uses: ./.github/workflows/configure-aws-amplify.yaml
    secrets: inherit
    with:
      ENV: staging

  build-android:
    name: Install and build android (PREVIEW)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: android
      PROFILE: preview

  build-ios:
    name: Install and build ios (PREVIEW)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: ios
      PROFILE: preview
