name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - develop
jobs:
  build-android:
    name: Install and build android (PREVIEW)
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: android
      PROFILE: preview

  build-ios:
    name: Install and build ios (PREVIEW)
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: ios
      PROFILE: preview
