name: EAS Submit

on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      PROFILE:
        required: false
        type: string
        default: production

jobs:
  submit:
    name: Install and submit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: git pull origin ${{github.ref_name}}

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: decode and store google service account
        env:
          GOOGLE_SERVICE_ACCOUNT_BASE64: ${{secrets.GOOGLE_SERVICES_ACCOUNT}}
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT_BASE64 | base64 --decode > service_account.json

      - name: submit on EAS
        run: eas submit --profile ${{inputs.PROFILE}} --platform ${{inputs.PLATFORM}} --non-interactive --latest
